title: jaagastudy
description: A New Kind of School for a New Way of Living.
url: "https://jaaga.github.io"
baseurl: "/jaagastudy"

navigation:
  - title: Home
    url: /
    nav_id: home
  - title: Bootcamp
    url: /bootcamps/creative-ai-bootcamp/01.html
    nav_id: bootcamp
  - title: Blog
    url: /blog.html
    nav_id: blog
  - title: Join Discord
    url: "https://discord.gg/ZtakuZXEF"
    external: true
    class: discord-btn

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      nav_id: blog

permalink: /blog/:title.html
